### ISSUE TITLE
Unable to sign-in

### ISSUE THREAD

**Issue by Susmita-Dey** [github/go-pipe#5]
## Problem description

I'm unable to login to view the documentation of `go-pipe` package. It seems like a bug.

## Devices

OS: Windows 11
Browser: Google Chrome

## Screenshot

![image](https://user-images.githubusercontent.com/79099734/204277199-79757e58-9917-45a7-b61d-4d0d382fe7f8.png)

**Comment by MrKrishnaAgarwal** [comment]
**Yes @github team, can you please look into this.
I'm also facing the same issue**

![image](https://user-images.githubusercontent.com/100597998/204305023-4ee117ff-986d-4d0d-8364-69813f1ef553.png)

**Comment by migue** [comment]
The original link was wrong, we have updated the README file with the proper one

**Comment by MrKrishnaAgarwal** [comment]
Okay, Thankyou 🌟
